version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/liftbridge-io/nats-on-a-log
    steps:
      - checkout
      - run: GO111MODULE=on go get -v -d ./...
      - run: GO111MODULE=on go test -v ./...
